config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many_attached :photos, dependent: :destroy
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :rooms
  has_one_attached :avatar
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @days = (@booking.end_date - @booking.start_date)/(60*60*24)
    #to access data booking from room
    @room = @booking.room
    @total = @days*@room.rate
    @photo = @room.photos.first
  end

  def new
    @booking = Booking.new(room_id: params[:room_id])
  end

  def create
    @booking = current_user.bookings.build(bookings_params)
    if @booking.save
      redirect_to @booking, notice: "Booking was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookings_params
    params.require(:booking).permit(:user, :room_id, :start_date, :end_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:description, :rate, :bathroom, :wifi, photos: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/new.html.erb
<%= form_with(model: @booking) do |form| %>

  <%= form.label :start_date %>
  <%= form.datetime_local_field :start_date %>

  <%= form.label :end_date %>
  <%= form.datetime_local_field :end_date %>

  <%= form.hidden_field :room_id %>

  <%= form.submit %>

<% end %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @photo %>
</p>

<p>start date: <%= @booking.start_date %> </p>

<p>end date: <%= @booking.end_date %> </p>

<p>days: <%= @days %> </p>

<p>
  <strong>Rate:</strong>
  <%= @room.rate %>
</p>

<p>
  <strong>Total:</strong>
  <%= @total %>
</p>


<%= link_to 'Stripe', "#" %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<% if user_signed_in? %>
  <%= link_to "Log Out",  destroy_user_session_path, method: :delete %>
  <%= link_to "Profile",  edit_user_registration_path %>
  <%= link_to "List Of Room",  rooms_path %>


<% else %>
  <%= link_to "Log In",  new_user_session_path %>
  <%= link_to "Sign Up",  new_user_registration_path %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @room.photos.each do |p|%>
   <%= image_tag p %>
  <% end %>

  <div class="field">
    <%= form.label :photos %>
    <%= form.file_field :photos, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate %>
  </div>

  <div class="field">
    <%= form.label :bathroom %>
    <%= form.number_field :bathroom %>
  </div>

  <div class="field">
    <%= form.label :wifi %>
    <%= form.check_box :wifi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms List</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Description</th>
      <th>Rate</th>
      <th>Bathroom</th>
      <th>Wifi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <% @rooms.each do |room| %>
        <tr>
          <td><% room.photos.each do |p| %>
          <%=image_tag p, width: 100%>
          <% end %>
          </td>
          <td><%= room.description %></td>
          <td><%= room.rate %></td>
          <td><%= room.bathroom %></td>
          <td><% if room.wifi %>
              /
              <% else%>
              x
              <% end %>
          </td>
          <td><%= link_to 'Show', room %></td>
          <td><%= link_to 'Edit', edit_room_path(room) %></td>
          <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>
<%= link_to 'Back', root_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photos:</strong>
  <% @room.photos.each do |p| %>
  <%=image_tag p, width: 100%>
  <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @room.rate %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @room.bathroom %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @room.wifi %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
<br>
<br>
<%= link_to 'Book Now', new_booking_url(room_id: @room.id) %>

app/views/shared/_flash_message.html.erb
<p class="notice"><%= notice %></p>